const Category = [
  // expense:
  [
    { title: "Housing", emoji: "🏠" },
    { title: "Mortgage or rent", emoji: "🏠" },
    { title: "Property taxes", emoji: "🧾" },
    { title: "Household repairs", emoji: "🏚️" },
    { title: "HOA fees", emoji: "🧾" },
    { title: "Transportation", emoji: "🚇" },
    { title: "Car payment", emoji: "🚗" },
    { title: "Car warranty", emoji: "🚗" },
    { title: "Car Fuel", emoji: "⛽" },
    { title: "Car Maintenance", emoji: "🚗" },
    { title: "Food", emoji: "🥗" },
    { title: "Beverage", emoji: "🧋" },
    { title: "Groceries", emoji: "🍅" },
    { title: "Restaurants", emoji: "🍕" },
    { title: "Pet food", emoji: "🐶" },
    { title: "Electricity Bill", emoji: "🔌" },
    { title: "Water Bill", emoji: "💧" },
    { title: "Phones", emoji: "📱" },
    { title: "Cable", emoji: "📺" },
    { title: "Internet", emoji: "📶" },
    { title: "Clothing", emoji: "👕" },
    { title: "Medical/Healthcare", emoji: "🏥" },
    { title: "Medications", emoji: "💊" },
    { title: "Health insurance", emoji: "❤️‍🩹" },
    { title: "Life insurance", emoji: "❤️‍🩹" },
    { title: "Household Items", emoji: "🧾" },
    { title: "Gym memberships", emoji: "🏋🏻‍♂️" },
    { title: "Haircuts", emoji: "💇🏻" },
    { title: "Cosmetics", emoji: "💅🏻" },
    { title: "Subscriptions", emoji: "🧾" },
    { title: "Loans", emoji: "🧾" },
    { title: "Credit card", emoji: "🧾" },
    { title: "Investing", emoji: "🧑🏻‍💻" },
    { title: "Education", emoji: "🧑🏻‍💻" },
    { title: "Gifts", emoji: "🎁" },
    { title: "Entertainment", emoji: "💻" },
    { title: "Alcohol/ bars", emoji: "🍻" },
  ],
  // income:
  [
    { title: "Salary", emoji: "💰" },
    { title: "Payment", emoji: "💰" },
    { title: "Returned by Friend", emoji: "🕺🏻" },
  ],
];
export default Category;
